#!/bin/bash

exec < /dev/tty

read -p "Do you want to build and push the images to Docker Hub? (yes/no) " yn

case $yn in 
	yes ) source ./build-and-push.sh;exit 0;;
	no )  exit;;
	* ) echo invalid response;
		exit 1;;
esac